### ISSUE TITLE
Rename to `jupyterlite-xeus`?

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/jupyterlite-xeus#1]
For simplicity and succinctness, maybe this package could be named `jupyterlite-xeus`? 

Which would be the name end users would be using in their build environments to deploy a JupyterLite site.

**Comment by DerThorsten** [comment]
fine with me (btw in the code the extension is still named xeus-python something something since it was created from the jupyterlite-xeus-python repo by copy pasting
