### ISSUE TITLE
How is `kernel.json` generated?

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/jupyterlite-xeus#3]
The code references this file:

https://github.com/DerThorsten/jupyterlite-xeus/blob/f386b6d515fd1741f727256ed3ccf684a2d988d3/src/index.ts#L43

How is this file generated?

Also, looks like it should be named `kernels.json` instead? (plural)

**Comment by DerThorsten** [comment]
this is **NOT** the list of all kernels, but the individual kernelspec of the kernels.
This is installed with the c++ package. Ie each xeus-lite kernel has this json file next to the wasm and js.

**Comment by jtpio** [comment]
ah ok. Where in the C++ package is this file generated at the moment?

**Comment by DerThorsten** [comment]
> ah ok. Where in the C++ package is this file generated at the moment?

for instance here
https://github.com/jupyter-xeus/xeus-sqlite/blob/main/share/jupyter/kernels/xsqlite/kernel.json.in

**Comment by jtpio** [comment]
ok thanks for the info :+1: 

Just trying to get an idea of the pattern for all xeus kernels. And whether would should / could implement this generation logic in a `jupyter-lite` CLI addon (like for `jupyterlite-xeus-python`) at the moment
